-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 17:07:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utente` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(512) NOT NULL,
  `data_nascita` DATETIME NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Via` VARCHAR(100) NOT NULL,
  `CAP` INT(5) NOT NULL,
  `Paese` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(2) NOT NULL,
  `Cellulare` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professione` (
  `idProfessione` INT NOT NULL AUTO_INCREMENT,
  `NomeProfessione` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessione`),
  UNIQUE INDEX `NomeProfessione_UNIQUE` (`NomeProfessione` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professionista` (
  `Professione_idProfessione` INT NOT NULL,
  `Utente_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Professione_idProfessione`, `Utente_email`),
  INDEX `fk_Professionista_Professione_idx` (`Professione_idProfessione` ASC),
  INDEX `fk_Professionista_Utente1_idx` (`Utente_email` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`Asta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asta` (
  `idAsta` INT NOT NULL AUTO_INCREMENT,
  `Utente_email` VARCHAR(255) NOT NULL,
  `Data_inizio` DATETIME NOT NULL,
  `Data_fine` DATETIME NOT NULL,
  `email_vincitore` VARCHAR(255) NULL,
  `Prezzo_partenza` DECIMAL(6,2) NOT NULL,
  `Prezzo_chiusura` DECIMAL(6,2) NULL,
  `Commento` VARCHAR(500) NOT NULL,
  `Professione_richiesta` INT NOT NULL,
  PRIMARY KEY (`idAsta`),
  INDEX `fk_Asta_Utente1_idx` (`Utente_email` ASC),
  INDEX `fk_Asta_Utente2_idx` (`email_vincitore` ASC),
  INDEX `fk_Asta_Professione1_idx` (`Professione_richiesta` ASC),
  CONSTRAINT `fk_Asta_Utente1`
    FOREIGN KEY (`Utente_email`)
    REFERENCES `mydb`.`Utente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asta_Utente2`
    FOREIGN KEY (`email_vincitore`)
    REFERENCES `mydb`.`Utente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asta_Professione1`
    FOREIGN KEY (`Professione_richiesta`)
    REFERENCES `mydb`.`Professione` (`idProfessione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lavoro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lavoro` (
  `Asta_idAsta` INT NOT NULL,
  `idLavoro` INT NOT NULL AUTO_INCREMENT,
  `Professionista_Professione_idProfessione` INT NOT NULL,
  `Professionista_Utente_email` VARCHAR(255) NOT NULL,
  `Recensione` VARCHAR(500) NULL,
  INDEX `fk_Lavoro_Asta1_idx` (`Asta_idAsta` ASC),
  PRIMARY KEY (`idLavoro`),
  INDEX `fk_Lavoro_Professionista1_idx` (`Professionista_Professione_idProfessione` ASC, `Professionista_Utente_email` ASC),
  CONSTRAINT `fk_Lavoro_Asta1`
    FOREIGN KEY (`Asta_idAsta`)
    REFERENCES `mydb`.`Asta` (`idAsta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lavoro_Professionista1`
    FOREIGN KEY (`Professionista_Professione_idProfessione` , `Professionista_Utente_email`)
    REFERENCES `mydb`.`Professionista` (`Professione_idProfessione` , `Utente_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
